import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { citationSystem } from '@/lib/ai/citation-system';
import { AuditLogger } from '@/lib/audit-logger';
import { RBAC } from '@/lib/rbac';

export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.email) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const userRole = (session.user as any).role || 'free';
    if (!RBAC.canAccessFeature(userRole, 'memo-generator')) {
      return NextResponse.json({ 
        error: RBAC.getUpgradeMessage('Legal Memo Generator') 
      }, { status: 403 });
    }

    const { topic, facts, legalIssues } = await request.json();

    if (!topic || typeof topic !== 'string') {
      return NextResponse.json({ error: 'Invalid topic provided' }, { status: 400 });
    }

    const research = await citationSystem.conductResearch(topic);
    const memo = generateLegalMemo(topic, facts || '', legalIssues || '', research);

    await AuditLogger.log({
      userId: session.user.id,
      action: 'generate_memo',
      resourceType: 'memo',
      ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
      metadata: { topic }
    });

    return NextResponse.json({
      success: true,
      memo
    });
  } catch (error) {
    console.error('Memo generation error:', error);
    return NextResponse.json({ error: 'Failed to generate memo' }, { status: 500 });
  }
}

function generateLegalMemo(topic: string, facts: string, legalIssues: string, research: any): string {
  const date = new Date().toLocaleDateString('en-IN', { 
    day: '2-digit', 
    month: 'long', 
    year: 'numeric' 
  });

  return `LEGAL MEMORANDUM

TO: Client
FROM: Legalify AI Legal Assistant
DATE: ${date}
RE: ${topic}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

I. QUESTION PRESENTED

${legalIssues || `What are the legal implications and applicable laws regarding ${topic}?`}

II. BRIEF ANSWER

Based on the research conducted, this matter is governed by relevant Indian statutes and case law. The following analysis provides a comprehensive overview of the legal position.

III. STATEMENT OF FACTS

${facts || `The matter concerns ${topic}. Further factual details should be provided for a more comprehensive analysis.`}

IV. LEGAL ANALYSIS

${research.summary}

A. Applicable Legal Framework

The following legal provisions are relevant to this matter:

${research.citations.filter((c: any) => c.type === 'statute').map((c: any, i: number) => 
  `${i + 1}. ${c.title}, ${c.year}\n   Reference: ${c.reference}`
).join('\n\n') || 'No specific statutes identified. General principles of Indian law apply.'}

B. Relevant Case Law

${research.citations.filter((c: any) => c.type === 'case').map((c: any, i: number) => 
  `${i + 1}. ${c.title}\n   Citation: ${c.reference}\n   Court: ${c.court || 'N/A'}`
).join('\n\n') || 'No directly applicable case law identified in current database.'}

C. Application to Present Facts

Based on the above legal framework, the following considerations apply:

1. The matter falls within the jurisdiction of Indian courts and is governed by applicable Indian statutes.

2. The legal principles established in the cited cases provide guidance on interpretation and application.

3. Compliance with procedural requirements under relevant statutes is essential.

4. The parties should be aware of their rights and obligations under the applicable legal framework.

V. CONCLUSION

${research.confidence > 0.7 ? 
  'The legal position is relatively clear based on existing statutes and precedents.' : 
  'The legal position requires further analysis and consultation with specialized legal counsel.'}

It is recommended that:
- All relevant documents be reviewed in detail
- Compliance with statutory requirements be ensured
- Professional legal advice be sought for specific actions
- All deadlines and procedural requirements be strictly followed

VI. LEGAL REFERENCES

${research.bibliography}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

DISCLAIMER: This memorandum is generated by AI and is for informational purposes only. 
It does not constitute legal advice. Please consult a qualified attorney for specific legal guidance.

Prepared by: Legalify AI Legal Assistant
Date: ${date}`;
}
