import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { citationSystem } from '@/lib/ai/citation-system';
import { AuditLogger } from '@/lib/audit-logger';
import { RBAC } from '@/lib/rbac';

export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.email) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const userRole = (session.user as any).role || 'free';
    if (!RBAC.canAccessFeature(userRole, 'argument-generator')) {
      return NextResponse.json({ 
        error: RBAC.getUpgradeMessage('Argument Generator') 
      }, { status: 403 });
    }

    const { caseFacts, legalIssue, side } = await request.json();

    if (!caseFacts || !legalIssue) {
      return NextResponse.json({ error: 'Case facts and legal issue required' }, { status: 400 });
    }

    const research = await citationSystem.conductResearch(legalIssue);
    const argument = generateLegalArgument(caseFacts, legalIssue, side || 'petitioner', research);

    await AuditLogger.log({
      userId: session.user.id,
      action: 'generate_argument',
      resourceType: 'argument',
      ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
      metadata: { legalIssue, side }
    });

    return NextResponse.json({ success: true, argument });
  } catch (error) {
    console.error('Argument generation error:', error);
    return NextResponse.json({ error: 'Failed to generate argument' }, { status: 500 });
  }
}

function generateLegalArgument(facts: string, issue: string, side: string, research: any): string {
  const sideTitle = side === 'petitioner' ? 'PETITIONER' : 'RESPONDENT';
  
  return `LEGAL ARGUMENTS ON BEHALF OF ${sideTitle}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

I. STATEMENT OF FACTS

${facts}

II. LEGAL ISSUE

${issue}

III. ARGUMENTS

A. Legal Framework

The present matter is governed by the following legal provisions:

${research.citations.filter((c: any) => c.type === 'statute').map((c: any, i: number) => 
  `${i + 1}. ${c.title}, ${c.year} (${c.reference})\n   This statute provides the legal foundation for the ${sideTitle.toLowerCase()}'s position.`
).join('\n\n')}

B. Precedential Support

The following judicial precedents support the ${sideTitle.toLowerCase()}'s case:

${research.citations.filter((c: any) => c.type === 'case').map((c: any, i: number) => 
  `${i + 1}. ${c.title}\n   Citation: ${c.reference}\n   Court: ${c.court || 'N/A'}\n   This case establishes principles directly applicable to the present matter.`
).join('\n\n')}

C. Application to Present Case

Based on the facts and applicable law:

1. **Factual Basis**: The facts clearly establish that ${side === 'petitioner' ? 'the petitioner has a valid claim' : 'the respondent has a strong defense'}.

2. **Legal Merit**: Under the applicable statutes and precedents cited above, ${side === 'petitioner' ? 'the petitioner is entitled to relief' : 'the respondent\'s position is legally sound'}.

3. **Equitable Considerations**: The principles of natural justice and equity support ${side === 'petitioner' ? 'granting the relief sought' : 'dismissing the petition'}.

4. **Public Interest**: ${side === 'petitioner' ? 'Granting relief' : 'Upholding the respondent\'s position'} serves the broader public interest and upholds the rule of law.

IV. PRAYER

In light of the above arguments and legal authorities, it is respectfully submitted that:

${side === 'petitioner' ? 
  `- The petition be allowed
- The relief sought be granted
- Costs be awarded to the petitioner
- Any other relief deemed fit be granted` :
  `- The petition be dismissed
- The respondent be exonerated
- Costs be awarded to the respondent
- Any other relief deemed fit be granted`}

V. LEGAL AUTHORITIES CITED

${research.citations.map((c: any, i: number) => 
  `${i + 1}. ${c.title}${c.year ? `, ${c.year}` : ''} (${c.reference})`
).join('\n')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

DISCLAIMER: These arguments are AI-generated for informational purposes. 
Consult a qualified attorney for case-specific legal advice.

Generated by: Legalify AI Legal Assistant
Date: ${new Date().toLocaleDateString('en-IN')}`;
}
